### ISSUE TITLE
Example for writeTuples should refer to body rather than requestBody

### ISSUE THREAD

**Issue by adriantam** [openfga/go-sdk#48]
### Description

The README example in Go-SDK uses inconsistent name.

### Version of SDK

v0.2.2

### Version of OpenFGA (if known)

N/A

### OpenFGA Flags/Custom Configuration Applicable

N/A

### Reproduction

The README example reads
```
body := ClientWriteRequest{
    Writes: &[]ClientTupleKey{ {
        User:     "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
        Relation: "viewer",
        Object:   "document:roadmap",
    }, {
        User:     "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
        Relation: "viewer",
        Object:   "document:budget",
    } },
    Deletes: &[]ClientTupleKey{ {
        User:     "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
        Relation: "writer",
        Object:   "document:roadmap",
    } }
}

options := ClientWriteOptions{
    // You can rely on the model id set in the configuration or override it for this specific request
    AuthorizationModelId: openfga.PtrString("01GAHCE4YVKPQEKZQHT2R89MQV"),
}
data, err := fgaClient.Write(context.Background()).Body(requestBody).Options(options).Execute()
```

Notice that we declare variable as `body` while the execute refers to `requestBody`.   

README has this inconsistent behaviour in a few places as well

### Expected behavior
Should refer to `body` instead of `requestBody`.

### Additional context
> Add any other context about the problem here.

**Comment by adriantam** [comment]
The fix should be made in https://github.com/openfga/sdk-generator/blob/main/config/clients/go/template/README_calling_api.mustache

**Comment by balaji-dongare** [comment]
@adriantam  Could you please assigne it to me?

**Comment by ewanharris** [comment]
Thanks for tackling this @balaji-dongare!

We follow the standard GitHub fork and PR process so you won't be able to push directly to this repo. You can find some documentation on this in the [GitHub docs](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project), if you already have the repo cloned you might need to [update the remote](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo#configuring-git-to-sync-your-fork-with-the-upstream-repository), `origin` should point to your personal fork.

**Comment by balaji-dongare** [comment]
@ewanharris  Thank you for the ice break, I raised the PR.
