### ISSUE TITLE
Cannot make calls to OpenFGA when exposed under path

### ISSUE THREAD

**Issue by nsklikas** [openfga/go-sdk#56]
### Description

In a lot of our deployments we use path based routing (e.g. `example.com/serviceA` proxies to service A, `example.com/serviceB` proxies to service B). It seems like the SDK does not support calling OpenFGA when it is exposed under a path (https://github.com/openfga/go-sdk/blob/main/utils.go#L336).

### Reproduction

1. Initialize OpenFGA server
2. Use a reverse proxy to expose OpenFGA under a path
3. Try to make calls to the server through the proxy using the SDK

### Expected behavior

We would like to be able to use the SDK to make calls to an OpenFGA server that is exposed under a path.

**Comment by rhamzeh** [comment]
Thanks for the report @nsklikas - we're working on a fix
