### ISSUE TITLE
oauth2 package retains canonical import path from original code

### ISSUE THREAD

**Issue by bketelsen** [openfga/go-sdk#63]
### Description

oauth2 package retains canonical import path from original code, causing packages importing it to substitute the original golang.org/x/oauth2 package instead.

the `credentials` package in this repo imports `oauth2/clientcredentials` which has the canonical import path set to golang.org/x/oauth2.

**Comment by rhamzeh** [comment]
Thanks for your report and your PR @bketelsen - this has now been released in [v0.3.1](https://github.com/openfga/go-sdk/releases/tag/v0.3.1)
